LOCAL_PATH := device/micromax/a106
USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/micromax/a106/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6582
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := a106

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

# Use CM PowerHAL by default
TARGET_POWERHAL_VARIANT := cm

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 943718400
BOARD_USERDATAIMAGE_PARTITION_SIZE := 968884224
BOARD_FLASH_BLOCK_SIZE := 131072


#BOARD_CUSTOM_BOOTIMG_MK := $(LOCAL_PATH)/boot.mk
TARGET_PREBUILT_KERNEL := $(LOCAL_PATH)/kernel

BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x00008000 --ramdisk_offset 0x01000000 --tags_offset 0x00000100

TARGET_RECOVERY_FSTAB := $(LOCAL_PATH)/root/fstab.mt6582
TARGET_PREBUILT_RECOVERY_KERNEL := $(LOCAL_PATH)/kernel
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_GLOBAL_CFLAGS   += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_USERIMAGES_USE_EXT4:=true
BOARD_CUSTOM_BOOTIMG_MK := $(LOCAL_PATH)/boot.mk
#TARGET_COMMON_NAME := Lenovo S939
BOARD_USE_MTK_LAYOUT := true
BOARD_MTK_BOOT_LABEL := "/bootimg"
#BOARD_USE_NTFS_3G := false
#BRIGHTNESS_SYS_FILE := "/sys/class/leds/lcd-backlight/brightness"
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/mt_usb/musb-hdrc.0/gadget/lun%d/file"
#TARGET_SCREEN_HEIGHT := 1280
#TARGET_SCREEN_WIDTH := 720
